src/Obsidian/Controllers/OAuth/OAuth20Controller.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Obsidian.Application.Authentication;
using Obsidian.Application.OAuth20;
using Obsidian.Application.OAuth20.AuthorizationCodeGrant;
using Obsidian.Application.OAuth20.ImplicitGrant;
using Obsidian.Application.OAuth20.ResourceOwnerPasswordCredentialsGrant;
using Obsidian.Application.OAuth20.TokenVerification;
using Obsidian.Application.Services;
using Obsidian.Domain;
using Obsidian.Foundation.ProcessManagement;
using Obsidian.Misc;
using Obsidian.Models.OAuth;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;
using System.Threading.Tasks;

#pragma warning disable CS1591

namespace Obsidian.Controllers.OAuth
{
    [ApiExplorerSettings(IgnoreApi = true)]
    [Authorize(AuthenticationSchemes = ObsidianAuthenticationSchemes.OAuth20Cookie)]
    public class OAuth20Controller : Controller
    {
        private const string ProtectorKey = "Obsidian.OAuth.Context.Key";
        private readonly IDataProtector _dataProtector;
        private readonly SagaBus _sagaBus;
        private readonly IIdentityService _signinService;

        public OAuth20Controller(IDataProtectionProvider dataProtectionProvicer, SagaBus bus, IIdentityService signinService)
        {
            _dataProtector = dataProtectionProvicer.CreateProtector(ProtectorKey);
            _sagaBus = bus;
            _signinService = signinService;
        }

        #region Actions

        [HttpGet("oauth20/authorize")]
        [ValidateModel]
        [AllowAnonymous]
        public async Task<IActionResult> Authorize([FromQuery]AuthorizationRequestModel model)
        {
            if (!TryConvertToGrantType(model.ResponseType, out var grantType))
            {
                return BadRequest();
            }

            OAuth20Result result;
            switch (grantType)
            {
                case AuthorizationGrant.AuthorizationCode:
                    result = await StartAuthorizationCodeGrantAsync(model);
                    break;

                case AuthorizationGrant.Implicit:
                    result = await StartImplicitGrantAsync(model);
                    break;

                default:
                    return BadRequest();
            }
            if (result.State == OAuth20State.RequireSignIn)
            {
                return await SignInPageView(result);
            }
            return BadRequest();
        }

        [HttpPost("oauth20/authorize")]
        [ValidateModel]
        [AllowAnonymous]
        public async Task<IActionResult> SignIn([FromForm]OAuthSignInModel model)
        {
            var context = _dataProtector.Unprotect(model.ProtectedOAuthContext);
            if (!Guid.TryParse(context, out var sagaId))
            {
                return BadRequest();
            }
            User currentUser;
            if (model.IsAutoSignIn)
            {
                currentUser = await _signinService.GetCurrentUserAsync();
                if (currentUser.UserName != model.UserName)
                {
                    return BadRequest();
                }
            }
            else
            {
                var authResult = await PasswordAutnenticateAsync(model.UserName, model.Password);
                if (!authResult.IsCredentialValid)
                {
                    ModelState.AddModelError(nameof(OAuthSignInModel.UserName), "Invaild user name");
                    ModelState.AddModelError(nameof(OAuthSignInModel.Password), "Or invaild password");
                    return View("SignIn", model);
                }
                currentUser = authResult.User;
            }
            return await OAuth20SignIn(sagaId, currentUser, model.RememberMe || model.IsAutoSignIn);
        }

        [HttpPost("oauth20/authorize/permission")]
        [ValidateModel]
        public async Task<IActionResult> PermissionGrant([FromForm]PermissionGrantModel model)
        {
            var context = _dataProtector.Unprotect(model.ProtectedOAuthContext);
            if (!Guid.TryParse(context, out var sagaId))
            {
                return BadRequest();
            }
            var message = new PermissionGrantMessage(sagaId)
            {
                GrantedScopeNames = model.GrantedScopeNames ?? new List<string>()
            };
            var result = await _sagaBus.SendAsync<PermissionGrantMessage, OAuth20Result>(message);
            switch (result.State)
            {
                case OAuth20State.AuthorizationCodeGenerated:
                    return AuthorizationCodeRedirect(result);

                case OAuth20State.Finished:
                    return ImplictTokenRedirect(result);

                case OAuth20State.UserDenied:
                    return View("UserDenied");

                default:
                    return BadRequest();
            }
        }

        [HttpGet("oauth20/signout")]
        [ValidateModel]
        public async Task<IActionResult> SignOut([FromQuery(Name = "redurect_uri"), Url]string redirectUri)
        {
            await _signinService.CookieSignOutCurrentUserAsync(ObsidianAuthenticationSchemes.OAuth20Cookie);
            return Redirect(redirectUri);
        }

        [HttpPost("oauth20/switchuser")]
        [ValidateModel]
        public async Task<IActionResult> SignOut([FromForm]OAuthSignOutModel model)
        {
            var context = _dataProtector.Unprotect(model.ProtectedOAuthContext);
            if (!Guid.TryParse(context, out var sagaId))
            {
                return BadRequest();
            }
            var message = new CancelMessage(sagaId);
            var result = await _sagaBus.SendAsync<CancelMessage, OAuth20Result>(message);
            switch (result.State)
            {
                case OAuth20State.Cancelled:
                    await _signinService.CookieSignOutCurrentUserAsync(ObsidianAuthenticationSchemes.OAuth20Cookie);
                    return Redirect(CancelRedirectUrl(result.CancelData));

                default:
                    return BadRequest();
            }
        }

        [HttpPost("oauth20/token")]
        [ValidateModel]
        [AllowAnonymous]
        public async Task<IActionResult> Token([FromBody]AuthorizationCodeGrantRequestModel model)
        {
            if ("authorization_code".Equals(model.GrantType, StringComparison.OrdinalIgnoreCase))
            {
                var message = new AccessTokenRequestMessage(model.Code)
                {
                    ClientId = model.ClientId,
                    ClientSecret = model.ClientSecret,
                    Code = model.Code,
                    RedirectUri = model.RedirectUri
                };
                var result = await _sagaBus.SendAsync<AccessTokenRequestMessage, OAuth20Result>(message);
                switch (result.State)
                {
                    case OAuth20State.AuthorizationCodeGenerated:
                        return BadRequest();

                    case OAuth20State.Finished:
                        return Ok(TokenResponseModel.FromOAuth20Result(result));
                }
            }
            return BadRequest();
        }

        [HttpPost("oauth20/token_resource_owner_credential")]
        [ValidateModel]
        [AllowAnonymous]
        public async Task<IActionResult> Token([FromBody]ResourceOwnerPasswordCredentialsGrantRequestModel model)
        {
            if ("password".Equals(model.GrantType, StringComparison.OrdinalIgnoreCase))
            {
                var signinCommand = new PasswordAuthenticateCommand
                {
                    UserName = model.UserName,
                    Password = model.Password
                };
                var authResult = await _sagaBus.InvokeAsync<PasswordAuthenticateCommand, AuthenticationResult>(signinCommand);
                if (!authResult.IsCredentialValid)
                {
                    return Unauthorized();
                }
                var authorizeCommand = new ResourceOwnerPasswordCredentialsGrantCommand
                {
                    ClientId = model.ClientId,
                    User = authResult.User,
                    ClientSecret = model.ClientSecret,
                    ScopeNames = model.Scope.Split(' ')
                };
                var oauthResult = await _sagaBus.InvokeAsync<ResourceOwnerPasswordCredentialsGrantCommand, OAuth20Result>(authorizeCommand);
                switch (oauthResult.State)
                {
                    case OAuth20State.Finished:
                        return Ok(TokenResponseModel.FromOAuth20Result(oauthResult));

                    default:
                        return BadRequest();
                }
            }
            return BadRequest();
        }

        [HttpPost("oauth20/token/verify")]
        [ValidateModel]
        [AllowAnonymous]
        public async Task<IActionResult> VerifyToken(TokenVerificationModel model)
        {
            var command = new VerifyTokenCommand
            {
                ClientId = model.ClientId,
                Token = model.Token
            };
            var result = await _sagaBus.InvokeAsync<VerifyTokenCommand, bool>(command);
            return Ok(result);
        }

        #endregion Actions

        private async Task<OAuth20Result> StartImplicitGrantAsync(AuthorizationRequestModel model)
        {
            var command = new ImplicitGrantCommand
            {
                ClientId = model.ClientId,
                ScopeNames = model.Scope.Split(' '),
                RedirectUri = model.RedirectUri
            };
            return await _sagaBus.InvokeAsync<ImplicitGrantCommand, OAuth20Result>(command);
        }

        private async Task<OAuth20Result> StartAuthorizationCodeGrantAsync(AuthorizationRequestModel model)
        {

src/Obsidian/Views/OAuth20/PermissionGrant.cshtml
@using Obsidian.Domain
@using Obsidian.Models.OAuth
@model PermissionGrantModel
@{
    ViewData["Title"] = "Grant Permissions";
    var client = ViewBag.Client as Client;
    var scopes = ViewBag.Scopes as IList<PermissionScope>;
    var i = 0;
}
<div class="fullscreen">
    <div class="text-padding left-div">
        @*Left Section*@
        <h1>Permission</h1>
        <h3>Allow &ensp;<b>@client.DisplayName</b>&ensp; to access these following information?</h3>
    </div>
    <div class="form form-padding">
        @*Right Section*@
        <form asp-action="PermissionGrant" asp-controller="OAuth20" class="text-padding">
            <ul class="list-group text-padding">
                @foreach (var scope in scopes)
                {
                    var id = $"{nameof(Model.GrantedScopeNames)}_{ ++i}";
                    <li class="list-group-item list-group-item-info">
                        <div class="checkbox checkbox-primary">
                            <label class="list-group-item-right">
                                <input
                                    name="@nameof(Model.GrantedScopeNames)" id="@id"
                                    type="checkbox" value="@scope.ScopeName" />
                            </label>
                        </div>
                        <h4 class="list-group-item-heading">@scope.DisplayName</h4>
                        <p class="list-group-item-text">@scope.Description</p>
                    </li>
                }
            </ul>
            <input asp-for="ProtectedOAuthContext" type="hidden" />
            <button class="btn btn-lg btn-info btn-block btn-raised" type="submit">Next</button>
        </form>
    </div>
</div>
<link href="~/css/SignIn.css" rel="stylesheet" />

src/Obsidian/Views/OAuth20/SignIn.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Obsidian.Models.OAuth.OAuthSignInModel
@using Obsidian.Domain
@{
    ViewData["Title"] = "Sign in";
    var profile = ViewData["UserProfile"] as UserProfile;
}
<div class="fullscreen">

    <div class="text-padding left-div center">
        @*Left Section*@
        <h1>Obsidian</h1>
        <h3>One-stop Authenication Solution</h3>
    </div>
    @*Right Section*@
    <div class="right-div form-size form-white">
        @if (Model.IsAutoSignIn)
            {
            <div class="form-content">
                <form role="form" class="text-padding" asp-action="Authorize" asp-controller="OAuth20">
                <h3 class="center">Hello @Model.UserName!</h3>
                
                    <div class="face-wrapper">
                        <div class="bouncer">:)</div>
                    </div>
                <script>
                    setTimeout(function(){
                        $("form").submit();
                    },3000);
                </script>
                <input asp-for="UserName" type="hidden" />
                <input asp-for="ProtectedOAuthContext" type="hidden" />
                <input asp-for="RememberMe" type="hidden" />
                <input asp-for="IsAutoSignIn" type="hidden" />
                <button class="btn btn-lg btn-primary btn-block btn-raised" type="submit">Sign In</button>
            </form>

            <form role="form" class="text-padding" asp-action="SignOut" asp-controller="OAuth20">
                <input asp-for="ProtectedOAuthContext" type="hidden" />
                <button class="btn btn-lg btn-primary btn-block btn-raised" type="submit">Switch user / Sign out</button>
            </form>
            </div>
        }
        else
        {
            <form role="form" class="text-padding form-content" asp-action="Authorize" asp-controller="OAuth20">
                <div class="form-group">
                    <label asp-for="UserName" class="control-label"></label>
                    <input asp-for="UserName" class="form-control" type="text" placeholder="Enter your E-mail address" required />
                </div>
                <div class="form-group">
                    <label class="control-label" asp-for="Password"></label>
                    <input class="form-control" asp-for="Password" type="password" placeholder="Enter your password" required />
                </div>

                <div class="checkbox checkbox-primary">
                    <label asp-for="RememberMe">
                        <input type="checkbox" asp-for="RememberMe" />
                        Remember Me
                    </label>
                </div>
                <br />
                <input asp-for="ProtectedOAuthContext" type="hidden" />
                <input asp-for="IsAutoSignIn" type="hidden" />
                <button class="btn btn-lg btn-primary btn-block btn-raised" type="submit">Sign In</button>
            </form>
        }
    </div>

</div>


<link href="~/css/SignIn.css" rel="stylesheet" />

src/Obsidian/Views/OAuth20/UserDenied.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Access Denied";
}
<div class="fullscreen">
    <div class="text-padding left-div">
        @*Left Section*@
        <h1>Denied</h1>
        <h3>Access denied.</h3>
        
    </div>
    <div class="form form-padding">
        @*Right Section*@
        <i class="fa fa-exclamation-triangle warning"></i>
        <h3 class="text-padding">
            Your request is denied due to security reasons.
            Contact administrators if this is a bug. Sorry for any inconvience.
        </h3>
    </div>
</div>
<link href="~/css/SignIn.css" rel="stylesheet" />